### PR TITLE
Add ruby:2.3.3-node-chrome

### PR DESCRIPTION
**Pull request by starsirius**
I already pushed the image [here](https://hub.docker.com/r/artsy/ruby/tags/) and it's used by https://github.com/artsy/ohm/pull/471.

### CODE REVIEW

**Comment by starsirius** [comment]
Not sure why CircleCI is picking this up. Maybe we should just stop building it? https://circleci.com/gh/artsy/docker-images

**Comment by jonallured** [comment]
Yeah, I agree, we should just not build this project. 👍

**Comment by starsirius** [comment]
Don't know how to do that. There is supposed a "Stop building" here: https://circleci.com/gh/artsy/docker-images/edit. I don't see it even logged in as it@. 🤔

**Comment by jonallured** [comment]
Ooh, hrm...that's exactly where I was expecting to see it as well!

**Comment by bhoggard** [comment]
It's on github: webhooks, etc. I will delete it.

**Pull request merged**
